name:                Functions-And-Dragons
version:             0.1.0.0
github:              "Emersont1/Functions-And-Dragons"
license:             MIT
author:              "Peter Taylor"
maintainer:          "pmy@pt3.uk"
copyright:           "2020 Peter Taylor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Functions-And-Dragons#readme>

dependencies:
- base >= 4.7 && < 5
- containers 

library:
  source-dirs: src

executables:
  Functions-And-Dragons-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Functions-And-Dragons

tests:
  Functions-And-Dragons-Duel-Test:
    main:                Main.hs
    source-dirs:         test/DuelTest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    dependencies:
    - Functions-And-Dragons
